name: SSHd tests - NOGIL

on:
  push:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    steps:    
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
    - uses: actions/checkout@v4
    - name: Set up Python 3.14
      uses: actions/setup-python@v6    
    - name : Setup free threded python
      uses: deadsnakes/action@v3.2.0
      with:
        python-version: 3.14
        # debug: true  # Optional, to select a Python debug build
        nogil: true  # Optional, to select a free-threaded Python build (3.13+ only)
    - name: Test Machine Info
      run: |
            df
            free
            cat /proc/cpuinfo
    - name: Install Debian Packages
      run: |
          sudo apt update
          sudo apt-get install -y graphviz python3-sklearn python3-pandas python3-matplotlib jupyter-notebook python3-ipython python3-scipy python3-numpy python3-pydot python3-setproctitle python3-objgraph python3-urllib3 python3-imageio time btop
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install --progress-bar off numpy scipy pandas scikit-learn matplotlib pydot jupyter xgboost ipython lightgbm statsmodels setproctitle urllib3 objgraph imageio imageio_ffmpeg
    - name: Initial Cleanup
      run : |
            mkdir -p logs
            fc-cache 	
    - name: Check Installed Versions
      run : |
            export PYTHONPATH=$PYTHONPATH:.
            export PYTHON_GIL=0
            python ./tests/display_version_info.py
